---
- name: Main configuration server playbook
  hosts: all
  # hosts: webservers
  become: yes
  # Services  |	Description	                                    |   Ports
    # Vote	    |   Voting form (Flask) 	                        |   80 
    # Result    |	Result service (Node.js + WebSocket)            |   3000
    # Redis	    |   Temporary storage for votes	                    |   6379
    # Worker	|   Proccess in the background (Node.js)            |   — (no port exposed)
    # PostgreSQL|	Database for the results                    	|   5432
    
  tasks:
    - name: Install essentials packages
      apt:
        name: ["curl", "git", "redis-server", "postgresql", "python3-pip", "python3-venv"]
        state: present
        update_cache: yes

    - name: Add NodeSource repository for Node.js 20.x
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -      

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install Python packages
      pip:
        name: ["django", "djangorestframework", "psycopg2-binary", "redis", "gunicorn"]
        state: present
    
    - name: Crear base de datos votes (workaround)
      become: yes
      shell: |
        sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'votes'" | grep -q 1 || sudo -u postgres createdb votes
    
    - name: Asignar contraseña al usuario postgres
      become: yes
      shell: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"